services:

  nginx:
    container_name: nginx
    image: nginx:0.1.0-alpine3.19
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - /home/smoroz/data/wordpress:/var/www/html:rw
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
    networks:
      - public

  mariadb:
    container_name: mariadb
    image: mariadb:10.11.6-alpine3.19
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - /home/smoroz/data/mariadb:/var/lib/mysql:rw
    env_file:
      - .env
    secrets:
      - mysql_root_user
      - mysql_root_password
      - wp_admin_user
      - wp_admin_password
    restart: unless-stopped
    networks:
      - public

  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-alpine3.19
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - /home/smoroz/data/wordpress:/var/www/html:rw
    env_file:
      - .env
    secrets:
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
      - wp_user_email
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - public

networks:
  public:
    driver: bridge
    name: public

secrets:
  mysql_root_user:
    file: ../secrets/db_root_user.txt
  mysql_root_password:
    file: ../secrets/db_root_password.txt

  # Wordpress admin
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt

  # Wordpress user
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
