services:

  nginx:
    container_name: nginx
    image: nginx:0.1.0-alpine3.19
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - public

networks:
  public:
